name: CI

on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm run install:clean

    - name: Compilar aplicação Angular
      run: npm run build

    - name: Construir imagem Docker
      run: docker build -t fazenda-non .

    - name: Criar tag para versionamento da imagem docker
      run: docker tag fazenda-non impostos/fazenda-non-homolog:latest

    - name: Fazer login no Docker Hub
      uses: docker/login-action@v1
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASS }}'

    - name: Enviar a imagem criada para o DockerHub
      run: docker push impostos/fazenda-non-homolog:latest

    - name: Entrar no servidor da aplicação Angular
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        host: ${{ secrets.SERVER_CLOUD_HOST }}
        user: ${{ secrets.SERVER_CLOUD_USER }}
        pass: '${{ secrets.SERVER_CLOUD_PASS }}'
        script: |
            echo '${{ secrets.CLOUD_PASS }}'|sudo -S docker rm fazenda-non-homolog -f
            echo '${{ secrets.SERVER_CLOUD_PASS }}'|sudo -S docker rmi $(echo '${{ secrets.SERVER_CLOUD_PASS }}'|sudo -S docker images impostos/fazenda-non-homolog -a -q) -f
            echo '${{ secrets.SERVER_CLOUD_PASS }}'|sudo -S docker run --name fazenda-non-homolog -p 9005:80 -d -t impostos/fazenda-non-homolog:latest
