name: CI

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Compilar aplicação Angular
      run: npm run build:prod

    - name: Construir imagem Docker
      run: docker build -t rms-ui .

    - name: Criar tag para versionamento da imagem docker
      run: docker tag rms-ui goodvandro/rms-ui:latest

    - name: Fazer login no Docker Hub
      uses: docker/login-action@v1
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASS }}'

    - name: Enviar a imagem criada para o DockerHub
      run: docker push goodvandro/rms-ui:latest

    # - name: Entrar no servidor da aplicação Angular
    #   uses: cross-the-world/ssh-pipeline@v1.2.0
    #   with:
    #     host: ${{ secrets.SERVER_CLOUD_HOST }}
    #     user: ${{ secrets.SERVER_CLOUD_USER }}
    #     pass: '${{ secrets.SERVER_CLOUD_PASS }}'
    #     script: |
    #         echo '${{ secrets.SERVER_CLOUD_PASS }}'|sudo -S docker run --name rms-ui -p 4200:80 -d -t goodvandro/rms-ui:latest
